"""add review

Revision ID: 6760ad1e7a83
Revises: 1434e6da7bd4
Create Date: 2025-12-02 08:19:11.405539

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6760ad1e7a83"
down_revision: Union[str, Sequence[str], None] = "1434e6da7bd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column("review", sa.Column("rating", sa.Integer(), nullable=False))
    op.add_column(
        "review",
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("review", sa.Column("shipment_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "review", "shipment", ["shipment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "review", type_="foreignkey")
    op.drop_column("review", "shipment_id")
    op.drop_column("review", "comment")
    op.drop_column("review", "rating")
    op.drop_column("review", "created_at")
    # ### end Alembic commands ###
