"""add client contact

Revision ID: 8a3731ff7d41
Revises: 6ef47b8e842a
Create Date: 2025-11-25 08:38:06.641634

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a3731ff7d41"
down_revision: Union[str, Sequence[str], None] = "6ef47b8e842a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment",
        sa.Column(
            "client_contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "shipment", sa.Column("client_contact_phone", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipment", "client_contact_phone")
    op.drop_column("shipment", "client_contact_email")
    # ### end Alembic commands ###
