"""added delivery partner

Revision ID: 9b9a8c59ef2b
Revises: 
Create Date: 2025-11-19 23:45:14.136166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9a8c59ef2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_code', sa.ARRAY(sa.INTEGER()), nullable=True))
    op.add_column('delivery_partner', sa.Column('max_handling_capacity', sa.Integer(), nullable=False))
    op.add_column('delivery_partner', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('delivery_partner', 'address')
    op.add_column('seller', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('shipment', 'created_at')
    op.drop_column('seller', 'created_at')
    op.add_column('delivery_partner', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('delivery_partner', 'created_at')
    op.drop_column('delivery_partner', 'max_handling_capacity')
    op.drop_column('delivery_partner', 'serviceable_zip_code')
    # ### end Alembic commands ###
