"""added tag

Revision ID: e9fb922781f5
Revises: 6760ad1e7a83
Create Date: 2025-12-04 12:28:15.983733

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9fb922781f5"
down_revision: Union[str, Sequence[str], None] = "6760ad1e7a83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "EXPRESS",
                "STANDARD",
                "FRAGILE",
                "HEAVY",
                "INTERNATIONAL",
                "DOMESTIC",
                "TEMPERATURE_CONTROLLED",
                "GIFT",
                "RETURN",
                "DOCUMENT",
                name="tagname",
            ),
            nullable=False,
        ),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment_tag",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id", "tag_id"),
    )
    # ### end Alembic commands ###

    # Insert default tag entries
    op.execute(
        """
        INSERT INTO tag (id, name, instruction) VALUES
        (gen_random_uuid(), 'EXPRESS', 'Priority handling required. Deliver within 24 hours.'),
        (gen_random_uuid(), 'STANDARD', 'Standard delivery timeline. Process during regular schedule.'),
        (gen_random_uuid(), 'FRAGILE', 'Handle with extreme care. Avoid rough handling and stacking heavy items on top.'),
        (gen_random_uuid(), 'HEAVY', 'Item exceeds 10kg. Requires two-person lift and appropriate equipment.'),
        (gen_random_uuid(), 'INTERNATIONAL', 'Cross-border shipment. Ensure customs documentation is complete.'),
        (gen_random_uuid(), 'DOMESTIC', 'Local delivery within country borders. No customs clearance needed.'),
        (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Maintain temperature range as specified. Use refrigerated transport.'),
        (gen_random_uuid(), 'GIFT', 'Gift wrapping included. Handle packaging with care to preserve presentation.'),
        (gen_random_uuid(), 'RETURN', 'Return shipment. Process according to return merchandise authorization.'),
        (gen_random_uuid(), 'DOCUMENT', 'Contains important documents. Keep dry and protected from damage.')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_tag")
    op.drop_table("tag")
    # ### end Alembic commands ###

    ### add tage ent
